spring.application.name=supply_chain

# Environment variables for MongoDB configuration
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB}

# (Optional) Server Port Configuration (to avoid conflicts)
server.port=8081