spring.application.name=supply_chain

spring.data.mongodb.uri=mongodb+srv://admin:admin@supplychain.fkxkn.mongodb.net/
spring.data.mongodb.database=supply_chain

# (Optional) Server Port Configuration (to avoid conflicts)
server.port=8081